spring: 
  # sleuth   
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  host:
    connect-timeout-millis: 180000  # 3 min
    connection-request-timeout-millis: 180000
    socket-timeout-millis: 180000        
ribbon: 
  ReadTimeout: 180000
  ConnectTimeout: 180000 
  # config for tx-lcn
  MaxAutoRetriesNextServer: 0
feign:
  # enabling the request or response GZIP compression for your Feign requests 
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response: 
      enabled: true   
          
# tx-lcn distributed transaction client config  
tx-lcn: 
  client: 
    # Multiple separated by ",",such as 127.0.0.1:8070,127.0.0.2:8070
    manager-address: 127.0.0.1:8070
  ribbon: 
    loadbalancer: 
      dtx: 
        enabled: true
        
commonConfig: this is a common config tt