spring: 
  # sleuth   
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"  
zuul:
  host:
    connect-timeout-millis: 30000  # 30秒超时
    connection-request-timeout-millis: 30000
    socket-timeout-millis: 30000        
ribbon: 
  ReadTimeout: 30000
  ConnectTimeout: 30000		
hystrix: 
  command: 
    # hystrix 默认超时配置
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    # 指定具体类名、具体方法        
    "MyFeignClient#sayWhyByFeign()": 
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000   
commonConfig: this is a common config aa xx