spring: 
  # rabbitmq配置 
  rabbitmq:                   
    host: 192.168.2.6         # 主机地址
    port: 5672                # qmpq端口（默认5672）
    username: ms_client_test  # 用户名
    password: test1234        # 用户密码